name: bpp_shop
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0
#flutter build appbundle --build-name=1.0.2 --build-number=3

environment:
  sdk: ">=2.16.1 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
      sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  carousel_slider: ^4.0.0
  provider: ^6.0.2
  youtube_player_flutter: ^8.0.0
  intl: ^0.17.0
  flutter_switch: ^0.3.2
  #im_stepper: ^0.1.3
  video_player: ^2.3.0
  better_player: ^0.0.81
  chewie: ^1.1.0
  font_awesome_flutter: ^9.2.0
  flutter_image_slideshow: ^0.1.2
  pin_code_fields: ^7.4.0
  email_validator: ^2.0.1
  animated_flip_counter: ^0.2.4
  flutter_screenutil: ^5.0.3
  country_code_picker: ^2.0.2
  dcdg: ^4.0.1
  location: ^4.3.0
  google_fonts: ^2.2.0
  dotted_border: ^2.0.0+2
  flutter_launcher_icons: ^0.9.2
  modal_bottom_sheet: ^2.0.0
  vibration: ^1.7.4-nullsafety.0
  slider_button: ^2.0.0
  image_picker: ^0.8.4+8
  flutter_custom_clippers: ^2.0.0
  step_progress_indicator: ^1.0.2
  auto_size_text: ^3.0.0
  flutter_facebook_auth: ^4.1.2
  flutter_rating_bar: ^4.0.0
  google_maps_flutter: ^2.1.3
  http: ^0.13.4
  awesome_icons: ^1.1.0
  google_sign_in: ^5.3.0
  firebase_auth: ^3.3.16
  firebase_core: ^1.15.0
  path_provider_android: ^2.0.13
  shared_preferences: ^2.0.15
  flutter_html: ^3.0.0-alpha.3
  shimmer_animation: ^2.1.0
  fluttertoast: ^8.0.9
  rename: ^2.0.1
  animated_splash_screen: ^1.2.0
  time_range:
  im_stepper:
  flutter_spinkit: ^5.1.0
  new_version: ^0.3.1
  date_count_down: ^2.1.0
  date_time_format: ^2.0.1
  flutter_countdown_timer: ^4.1.0
  carousel_indicator: ^1.0.6
  smooth_page_indicator: ^1.0.0+2
  sms_autofill: ^2.2.0
dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.1.3+1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/fashionIcon.png"

flutter_native_splash:
  background_image: "images/splash1.png"
  andorid: true
  ios: true
  android_gravity: center
  ios_content_mode: center
  fullscreen: true
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/subApps/
    - assets/icons/
    - assets/drawer/
    - images/
#    - assets/images/
#    - images/ecom/men/watch/
#    - images/ecom/men/polo/
#    - images/ecom/woman/Sharee/
#    - images/ecom/woman/salwar/
#    - images/ecom/men/jeans/
#    - images/ecom/men/shoe/
#    - images/grocery/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
