import 'dart:convert';
import 'package:bpp_shop/models/bpp/district_model.dart';
import 'package:bpp_shop/models/bpp/devision_api_list.dart';
import 'package:bpp_shop/service/bpp/local_storage_service.dart';
import 'package:bpp_shop/view/bpp/address/order_proceed_screen.dart';
import 'package:bpp_shop/view_model/bpp/order_proceed_view_model.dart';
import 'package:http/http.dart'as http;
import 'package:provider/provider.dart';
import 'package:flutter/material.dart';


Future<List<Autogenerated>> getDistrictHttpRequest() async {

  String url = "https://bppshops.com/api/district/ajax/3";
  var result = await http.get(Uri.parse(url));
  // print(result.body);
  if(result.statusCode==200){
    final json = jsonDecode(result.body);
    //List<DistrictModel>? districtList;
    print(json);
    List<Autogenerated> districtList = json
        .map((item) => Autogenerated.fromJson(item))
        .toList()
        .cast<Autogenerated>();
    return districtList;
  }else{
    throw "Eror to get district.... status code: ${result.statusCode}";
  }

}
Future<List<division>> getPostOfficeHttpRequest(String id) async {
  List<division>? dhakaPostOfficeList;
  List<division>? dhakaCityPostOfficeList;
  String url = "https://bppshops.com/api/state/ajax/" + id.toString();
  var result = await http.get(Uri.parse(url));
    id=="1"?dhakaCityPostOfficeList = jsonDecode(result.body)
        .map((item) => division.fromJson(item))
        .toList()
        .cast<division>():dhakaPostOfficeList = jsonDecode(result.body)
        .map((item) => division.fromJson(item))
        .toList()
        .cast<division>();
    //subAreaListCopy=subAreaList;
  print(dhakaPostOfficeList);
  print(dhakaCityPostOfficeList);
  print(">>>>>>>>>>>>>>>Area<<<<<<<<<<<<<<<<");
  return id=="1"?dhakaCityPostOfficeList!:dhakaPostOfficeList!;

}

saveAddressHttps(BuildContext context,String streetAddress,String districtId,String thanaId,String phoneNumber) async {
  final token = await LocalStorageStore().getUserToken();
  Map data = {
    "street_address": streetAddress,
    "district_id": districtId,
    "thana_id": thanaId,
    "name": "Enter Your Name",
    "phone_no": phoneNumber,//_phoneNumberController.text,
  };
  var body = jsonEncode(data);
  var response =
  await http.post(Uri.parse("https://bppshops.com/api/checkout/store"),
    headers:{
      'Content-type': 'application/json',
      'Authorization':
      "Bearer ${token}", //47|ZSoxBWu2Nar7x6B4c7xIqxr4fmKmrjGNMHtwZ1lI"
    },
    body: body,
  );
  print("Response ???????????? : ${response.statusCode}");
  if (response.statusCode == 200){
    final orderProceedViewModel=Provider.of<OrderProceedViewModel>(context,listen: false);
    orderProceedViewModel.loadAddressList();
    Navigator.pushAndRemoveUntil(context,
        MaterialPageRoute(builder: (context) => OrderProceedScreen()), (route) => false);
  }else{
    throw "saveAddressHttps response error:code-${response.statusCode}";
  }
}